config/urls.py
from django.contrib import admin
from django.urls import path, include
from tsv.views import base_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', base_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('tsv/', include('tsv.urls')),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tsv/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views, answers_views, my_page_views

app_name = 'tsv'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('answers/detail/<int:answers_id>', base_views.detail, name='detail'),

    path('answers/create/weather/', answers_views.answers_weather, name='answers_weather'),
    path('answers/create/mood/', answers_views.answers_mood, name='answers_mood'),
    path('answers/create/wake_up/', answers_views.answers_wake_up, name='answers_wake_up'),
    path('answers/create/did_well/', answers_views.answers_did_well, name='answers_did_well'),
    path('answers/create/happiness/', answers_views.answers_happiness, name='answers_happiness'),
    path('answers/create/meal/', answers_views.answers_meal, name='answers_meal'),

    path('my_page/', my_page_views.my_page, name='my_page'),
    path('my_page/edit_profile/', my_page_views.edit_profile, name='edit_profile'),

]

tsv/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone


class Answers(models.Model) :
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    answer_date = models.CharField(max_length=30)
    cm_answer_date = models.DateTimeField(null=True)
    weather = models.CharField(max_length=80, null=True)
    mood = models.CharField(max_length=80, null=True)
    wake_up = models.CharField(max_length=30, null=True)
    did_well = models.CharField(max_length=100, null=True)
    happiness = models.CharField(max_length=100, null=True)
    breakfast = models.CharField(max_length=100, null=True)
    lunch = models.CharField(max_length=100, null=True)
    dinner = models.CharField(max_length=100, null=True)

class Profile(models.Model) :
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=10, blank=True)
    image = models.ImageField(blank=True, upload_to="%Y/%m/%d")

tsv/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from tsv.models import Answers, Profile
from django.contrib.auth.models import User

class WeatherForm(forms.ModelForm) :
    class Meta :
        model = Answers
        fields = ['weather']

        labels = {
            'weather' : '날씨',
        }
class MoodForm(forms.ModelForm) :
    class Meta :
        model = Answers
        fields = ['mood']

        labels = {
            'mood' : '기분',
        }
class WakeUpForm(forms.ModelForm) :
    class Meta :
        model = Answers
        fields = ['wake_up']

        labels = {
            'wake_up' : '일어난 시각',
        }
class DidWellForm(forms.ModelForm) :
    class Meta :
        model = Answers
        fields = ['did_well']

        labels = {
            'did_well' : '가장 잘한 일',
        }
class HappinessForm(forms.ModelForm) :
    class Meta :
        model = Answers
        fields = ['happiness']

        labels = {
            'happiness' : '가장 행복했던 일',
        }
class MealForm(forms.ModelForm) :
    class Meta :
        model = Answers
        fields = {
            'breakfast' : '아침',
            'lunch' : '점심',
            'dinner' : '저녁',
        }
class CustomUserChangeForm(UserChangeForm) :
    password = None
    username = forms.CharField(label="username", max_length=15, required=False)
    class Meta :
        model = User
        fields = ['email', 'username']
class ProfileForm(forms.ModelForm) :
    nickname = forms.CharField(label="nickname", max_length=15, required=False)
    image = forms.ImageField(label="profile_image", required=False)
    class Meta :
        model = Profile
        fields = ['nickname', 'image']

tsv/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.utils import timezone

from .forms import *
from .models import Answers
from .models import Profile

@login_required(login_url='common:login')
def index(request) :
    return render(request, 'tsv/index.html')

@login_required(login_url='common:login')
def answers_weather(request) :
    #만약 해당하는 데이터가 없다면 밑에 실행 아니면 else -> 함수로 따로 빼기
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = WeatherForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_mood')
    else:
        form = WeatherForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/weather_form.html', context)

@login_required(login_url='common:login')
def answers_mood(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = MoodForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_wake_up')
    else:
        form = MoodForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/mood_form.html', context)

@login_required(login_url='common:login')
def answers_wake_up(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = WakeUpForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_did_well')
    else:
        form = WakeUpForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/wake_up_form.html', context)

@login_required(login_url='common:login')
def answers_did_well(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = DidWellForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_happiness')
    else:
        form = DidWellForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/did_well_form.html', context)

@login_required(login_url='common:login')
def answers_happiness(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = HappinessForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_meal')
    else:
        form = HappinessForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/happiness_form.html', context)

@login_required(login_url='common:login')
def answers_meal(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = MealForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:index')
    else:
        form = MealForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/meal_form.html', context)

@login_required(login_url='common:login')
def my_page(request) :
    person, create = Profile.objects.get_or_create(user=request.user)
    today = Answers.objects.filter(username_id=request.user.id)
    context = {'person' : person, 'today' : today}
    return render(request, 'tsv/my_page.html', context)

@login_required(login_url='common:login')
def edit_profile(request) :
    if request.method == 'POST' :
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_change_form.is_valid() and profile_form.is_valid() :
            user_change_form.save()
            profile = profile_form.save(commit=False)
            profile.image = request.FILES['profile_image']
            profile.save()
            return redirect('tsv:my_page')
        return redirect('tsv:edit_profile')
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        profile, create = Profile.objects.get_or_create(user=request.user)
        profile_form = ProfileForm(instance=profile)
        context = {'user_change_form' : user_change_form, 'profile_form' : profile_form, 'person' : profile }
        return render(request, 'tsv/edit_profile_form.html', context)

@login_required(login_url='common:login')
def detail(request, answers_id) :
    answers = get_object_or_404(Answers, pk=answers_id)
    if request.user.id != answers.username_id :
        messages.error(request, '확인할 권한이 없습니다.')
        return redirect('tsv:my_page')
    context = {'answers' : answers}
    return render(request, 'tsv/detail.html', context)

tsv/views/answers_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.utils import timezone

from ..forms import *
from ..models import Answers

@login_required(login_url='common:login')
def answers_weather(request) :
    #만약 해당하는 데이터가 없다면 밑에 실행 아니면 else -> 함수로 따로 빼기
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = WeatherForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_mood')
    else:
        form = WeatherForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/weather_form.html', context)

@login_required(login_url='common:login')
def answers_mood(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = MoodForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_wake_up')
    else:
        form = MoodForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/mood_form.html', context)

@login_required(login_url='common:login')
def answers_wake_up(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = WakeUpForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_did_well')
    else:
        form = WakeUpForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/wake_up_form.html', context)

@login_required(login_url='common:login')
def answers_did_well(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = DidWellForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_happiness')
    else:
        form = DidWellForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/did_well_form.html', context)

@login_required(login_url='common:login')
def answers_happiness(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = HappinessForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:answers_meal')
    else:
        form = HappinessForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/happiness_form.html', context)

@login_required(login_url='common:login')
def answers_meal(request) :
    date = f'{datetime.now().year}-{datetime.now().month}-{datetime.now().day}'
    answer, is_exists = Answers.objects.get_or_create(username_id=request.user.id, answer_date=date)
    if request.method == 'POST':
        form = MealForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.cm_answer_date = timezone.now()
            answer.save()
            return redirect('tsv:index')
    else:
        form = MealForm(instance=answer)
    context = {'form': form}
    return render(request, 'tsv/meal_form.html', context)

tsv/views/base_views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Answers

@login_required(login_url='common:login')
def index(request) :
    return render(request, 'tsv/index.html')

@login_required(login_url='common:login')
def detail(request, answers_id) :
    answers = get_object_or_404(Answers, pk=answers_id)
    if request.user.id != answers.username_id :
        messages.error(request, '확인할 권한이 없습니다.')
        return redirect('tsv:my_page')
    context = {'answers' : answers}
    return render(request, 'tsv/detail.html', context)

tsv/views/my_page_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ..forms import *
from ..models import Answers
from ..models import Profile

@login_required(login_url='common:login')
def my_page(request) :
    person, create = Profile.objects.get_or_create(user=request.user)
    today = Answers.objects.filter(username_id=request.user.id)
    context = {'person' : person, 'today' : today}
    return render(request, 'tsv/my_page.html', context)

@login_required(login_url='common:login')
def edit_profile(request) :
    if request.method == 'POST' :
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_change_form.is_valid() and profile_form.is_valid() :
            user_change_form.save()
            profile = profile_form.save(commit=False)
            profile.image = request.FILES['profile_image']
            profile.save()
            return redirect('tsv:my_page')
        return redirect('tsv:edit_profile')
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        profile, create = Profile.objects.get_or_create(user=request.user)
        profile_form = ProfileForm(instance=profile)
        context = {'user_change_form' : user_change_form, 'profile_form' : profile_form, 'person' : profile }
        return render(request, 'tsv/edit_profile_form.html', context)

templates/tsv/answers_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘의 날씨는 어떤가요?</span>
    </div>
    <div class="select">
        <form method="post">
            {% csrf_token %}
            <ul>
                <li>
                    <input type="radio" value="sunny" id="sunny" name="weather" />
                    <label for="sunny"><img src='{% static 'images/sunny.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="cloudy" id="cloudy" name="weather" />
                    <label for="cloudy"><img src='{% static 'images/cloudy.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="rainy" id="rainy" name="weather" />
                    <label for="rainy"><img src='{% static 'images/rainy.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="snowy" id="snowy" name="weather" />
                    <label for="snowy"><img src='{% static 'images/snowy.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="windy" id="windy" name="weather" />
                    <label for="windy"><img src='{% static 'images/windy.png' %}' width="100" height="100" /></label>
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

templates/tsv/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="my-page-container">
        <div class="date">
            {{ answers.answer_date }}
        </div>
        <div class="top">
            {% if answers.weather == 'sunny' %}
            <div class="weather"><img src="{% static 'images/sunny.png' %}" width="45" height="45"></div>
            {% elif answers.weather == 'cloudy' %}
            <div class="weather"><img src="{% static 'images/cloudy.png' %}" width="45" height="45"></div>
            {% elif answers.weather == 'rainy' %}
            <div class="weather"><img src="{% static 'images/rainy.png' %}" width="45" height="45"></div>
            {% elif answers.weather == 'snowy' %}
            <div class="weather"><img src="{% static 'images/snowy.png' %}" width="45" height="45"></div>
            {% elif answers.weather == 'windy' %}
            <div class="weather"><img src="{% static 'images/windy.png' %}" width="45" height="45"></div>
            {% else %}
            <div class="weather">Blank</div>
            {% endif %}
            {% if answers.mood == 'happy' %}
            <div class="mood"><img src="{% static 'images/happy.png' %}" width="40" height="40"></div>
            {% elif answers.mood == 'soso' %}
            <div class="mood"><img src="{% static 'images/no-expression.png' %}" width="40" height="40"></div>
            {% elif answers.mood == 'surprised' %}
            <div class="mood"><img src="{% static 'images/surprised.png' %}" width="40" height="40"></div>
            {% elif answers.mood == 'sad' %}
            <div class="mood"><img src="{% static 'images/crying.png' %}" width="40" height="40"></div>
            {% elif answers.mood == 'angry' %}
            <div class="mood"><img src="{% static 'images/annoyed.png' %}" width="40" height="40"></div>
            {% else %}
            <div class="mood">Blank</div>
            {% endif %}
        </div>
        <div class="detail-content">
            <div class="content-color"></div>
            <div class="question">오늘 아침에 일어난 시간은?</div>
            <div class="answer">{{ answers.wake_up }}</div>
            <div class="question">오늘 내가 가장 잘한 일은?</div>
            <div class="answer">{{ answers.did_well }}</div>
            <div class="question">오늘 가장 행복했던 일은?</div>
            <div class="answer">{{ answers.happiness }}</div>
        </div>
        <div class="meal-box">
            <div class="breakfast-box">
                <div class="breakfast-text"></div>
                <div class="meal-text">Breakfast</div>
                <div class="menu-text">{{ answers.breakfast }}</div>

            </div>
            <div class="lunch-box">
                <div class="lunch-text"></div>
                <div class="meal-text">Lunch</div>
                <div class="menu-text">{{ answers.lunch }}</div>

            </div>
            <div class="dinner-box">
                <div class="dinner-text"></div>
                <div class="meal-text">Dinner</div>
                <div class="menu-text">{{ answers.dinner }}</div>

            </div>
        </div>
    </div>
{% endblock %}

templates/tsv/did_well_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘 가장 잘한 일은 무엇인가요?</span>
    </div>
    <form method="post" class="text-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="center">
            <input type="text" name="did_well" value="{{ form.did_well.value|default_if_none:'' }}" maxlength="50"/>
        </div>
        <div class="center">
            <button type="submit" class="next_btn">NEXT</button>
        </div>

    </form>

{% endblock %}

templates/tsv/edit_profile_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="my-page-container">
        <div class="left">
            Edit Profile
        </div>
        <form method="post" class="edit-profile-form" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'form_errors.html' %}
                <div class="filebox">
                    <span class="small-label">Profile image</span>
                    {% if not person.image == ''  %}
                    <img src="{{ person.image.url }}">
                    {% else %}
                    <img src="{% static 'images/profile_image.png' %}">
                    {% endif %}
                    <label for="profile_image">Choose image</label>
                    <input type="file" id="profile_image" name="profile_image" value="{{ form.image.value|default_if_none:'' }}" accept="image/*">
                </div>

                <div class="textbox">
                    <label for="username" class="small-label">Username</label>
                    <input type="text" placeholder="{{ user.username }}" name="username" id="username" value="{{ form.username.value|default:user.username }}" maxlength="15">
                    <label for="nickname" class="small-label">Name</label>
                    <input type="text" placeholder="{% if person.nickname %}{{ person.nickname }}{% else %}blank{% endif %}" name="nickname" id="nickname" value="{{ form.nickname.value|default:person.nickname }}">
                    <label for="email" class="small-label">Email</label>
                    <input type="email" placeholder="{{ user.email }}" name="email" id="email" value="{{ form.email.value|default:user.email }}">
                    <button type="submit" class="save_btn">Save</button>
                </div>

        </form>
    </div>
{% endblock %}

templates/tsv/happiness_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘 가장 행복했던 일은 무엇인가요?</span>
    </div>
    <form method="post" class="text-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="center">
            <input type="text" name="happiness" value="{{ form.happiness.value|default_if_none:'' }}" maxlength="50"/>
        </div>
        <div class="center">
            <button type="submit" class="next_btn">NEXT</button>
        </div>

    </form>

{% endblock %}

templates/tsv/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="center">
        <span>오늘 당신의 하루는 어떠셨나요?</span>
    </div>
    <div class="center">
        <span>하루를 마무리하면서 간단한 질문들을 통해 하루를 기록해보아요.</span>
    </div>
    <button type="button" class="start_btn" onclick="location.href='{% url 'tsv:answers_weather' %}'">START</button>

{% endblock %}

templates/tsv/meal_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘의 식사 메뉴는 무엇인가요?</span>
    </div>
    <form method="post" class="text-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div>
            <input type="text" id="breakfast" name="breakfast" placeholder="아침 메뉴" value="{{ form.breakfast.value|default_if_none:'' }}" maxlength="30"/>
            <input type="text" id="lunch" name="lunch" placeholder="점심 메뉴" value="{{ form.lunch.value|default_if_none:'' }}" maxlength="30"/>
            <input type="text" id="dinner" name="dinner" placeholder="저녁 메뉴" value="{{ form.dinner.value|default_if_none:'' }}" maxlength="30"/>
        </div>
        <div class="center">
            <button type="submit" class="next_btn">NEXT</button>
        </div>

    </form>

{% endblock %}

templates/tsv/mood_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘의 기분은 어떤가요?</span>
    </div>
    <form method="post" class="answer-form">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <ul>
                <li>
                    <input type="radio" value="happy" id="happy" name="mood" />
                    <label for="happy"><img src='{% static 'images/happy.png' %}' width="80" height="80" /></label>
                </li>
                <li>
                    <input type="radio" value="soso" id="soso" name="mood" />
                    <label for="soso"><img src='{% static 'images/no-expression.png' %}' width="80" height="80" /></label>
                </li>
                <li>
                    <input type="radio" value="surprised" id="surprised" name="mood" />
                    <label for="surprised"><img src='{% static 'images/surprised.png' %}' width="80" height="80" /></label>
                </li>
                <li>
                    <input type="radio" value="sad" id="sad" name="mood" />
                    <label for="sad"><img src='{% static 'images/crying.png' %}' width="80" height="80" /></label>
                </li>
                <li>
                    <input type="radio" value="angry" id="angry" name="mood" />
                    <label for="angry"><img src='{% static 'images/annoyed.png' %}' width="80" height="80" /></label>
                </li>
            </ul>
        <div class="center">
            <button type="submit" class="next_btn">NEXT</button>
        </div>

    </form>

{% endblock %}

templates/tsv/my_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="my-page-container">
        <div class="left">
            DashBoard
        </div>
        <div class="profile-box">
            <div class="center">
                {% if person.image %}
                    <img src="{{ person.image.url }}">
                {% else %}
                    <img src="{% static 'images/profile_image.png' %}">
                {% endif %}
            </div>
            <div class="profile-content">
                <div>
                    <p class="small-label">Username</p>
                    <span>{{ user.username }}</span>
                </div>
                <div>
                    <p class="small-label">Name</p>
                    <span>{% if person.nickname %}{{ person.nickname }}{% else %}&nbsp;&nbsp;{% endif %}</span>
                </div>
                <div>
                    <p class="small-label">Email</p>
                    <span>{{ user.email }}</span>
                </div>
            </div>
            <div class="center">
                <button type="button" class="edit-profile" onclick="location.href='{% url 'tsv:edit_profile' %}'">Edit Profile</button>
            </div>
        </div>
        {% if today %}
        <div class="mytoday-box">
            {% for t in today %}
                <div class="today-container">
                    <a href="{% url 'tsv:detail' t.id %}">{{ t.answer_date }}</a>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/tsv/wake_up_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘 몇시에 일어났나요?</span>
    </div>
    <form method="post" class="answer-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="center">
            <input type="time" class="wake_up_input" min="01:00" max="24:00" name="wake_up" value="{{ form.wake_up.value|default_if_none:'' }}" required/>
        </div>
        <div class="center">
            <button type="submit" class="next_btn">NEXT</button>
        </div>

    </form>

{% endblock %}

templates/tsv/weather_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="center">
        <span>오늘의 날씨는 어떤가요?</span>
    </div>
    <form method="post" class="answer-form">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <ul>
                <li>
                    <input type="radio" value="sunny" id="sunny" name="weather" />
                    <label for="sunny"><img src='{% static 'images/sunny.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="cloudy" id="cloudy" name="weather" />
                    <label for="cloudy"><img src='{% static 'images/cloudy.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="rainy" id="rainy" name="weather" />
                    <label for="rainy"><img src='{% static 'images/rainy.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="snowy" id="snowy" name="weather" />
                    <label for="snowy"><img src='{% static 'images/snowy.png' %}' width="100" height="100" /></label>
                </li>
                <li>
                    <input type="radio" value="windy" id="windy" name="weather" />
                    <label for="windy"><img src='{% static 'images/windy.png' %}' width="100" height="100" /></label>
                </li>
            </ul>
        <div class="center">
            <button type="submit" class="next_btn">NEXT</button>
        </div>

    </form>

{% endblock %}