common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from tsv.views import base_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', base_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('tsv/', include('tsv.urls')),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tsv/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views, answers_views, my_page_views

app_name = 'tsv'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('answers/detail/<int:answers_id>', base_views.detail, name='detail'),

    path('answers/create/weather/', answers_views.answers_weather, name='answers_weather'),
    path('answers/create/mood/', answers_views.answers_mood, name='answers_mood'),
    path('answers/create/wake_up/', answers_views.answers_wake_up, name='answers_wake_up'),
    path('answers/create/did_well/', answers_views.answers_did_well, name='answers_did_well'),
    path('answers/create/happiness/', answers_views.answers_happiness, name='answers_happiness'),
    path('answers/create/meal/', answers_views.answers_meal, name='answers_meal'),

    path('my_page/', my_page_views.my_page, name='my_page'),
    path('my_page/edit_profile/', my_page_views.edit_profile, name='edit_profile'),

]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm) :
    email = forms.EmailField()

    class Meta :
        model = User
        fields = ("username", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.
def signup(request) :
    if request.method == 'POST' :
        form = UserForm(request.POST)
        if form.is_valid() :
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else :
        form = UserForm()

    return render(request, 'common/signup.html', {'form' : form})

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="center">
        <h3>Sign in</h3>
    </div>
        <form method="post" class="login_form" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <input type="hidden" name="text" value="{{ next }}">
                <input class="username_input" type="text" placeholder="Enter username" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                <input type="password" placeholder="Enter password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
            <button type="submit" class="login_btn">Sign in</button>
        </form>
        <span class="login_bottom_text">아직 회원이 아니십니까?&nbsp;&nbsp;<a class="go_signup" href="{% url 'common:signup' %}">회원가입</a></span>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
    <div class="center">
        <h3>Sign up</h3>
    </div>
    <form method="post" class="login_form">
            {% csrf_token %}
            {% include 'form_errors.html' %}
                <input class="username_input" type="text" placeholder="Enter username" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                <input type="password" placeholder="Enter password" name="password1" id="password1" value="{{ form.password.value|default_if_none:'' }}">
                <input type="password" placeholder="Confirm password" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
                <input type="email" placeholder="Enter email" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        <button type="submit" class="login_btn">Sign up</button>
    </form>
    <span class="login_bottom_text">회원이십니까?&nbsp;&nbsp;<a class="go_signup" href="{% url 'common:login' %}">로그인</a></span>
{% endblock %}