common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from tsv.views import base_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', base_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('tsv/', include('tsv.urls')),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tsv/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views, answers_views, my_page_views

app_name = 'tsv'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('answers/detail/<int:answers_id>', base_views.detail, name='detail'),

    path('answers/create/weather/', answers_views.answers_weather, name='answers_weather'),
    path('answers/create/mood/', answers_views.answers_mood, name='answers_mood'),
    path('answers/create/wake_up/', answers_views.answers_wake_up, name='answers_wake_up'),
    path('answers/create/did_well/', answers_views.answers_did_well, name='answers_did_well'),
    path('answers/create/happiness/', answers_views.answers_happiness, name='answers_happiness'),
    path('answers/create/meal/', answers_views.answers_meal, name='answers_meal'),

    path('my_page/', my_page_views.my_page, name='my_page'),
    path('my_page/edit_profile/', my_page_views.edit_profile, name='edit_profile'),

]

tsv/views/base_views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Answers

@login_required(login_url='common:login')
def index(request) :
    return render(request, 'tsv/index.html')

@login_required(login_url='common:login')
def detail(request, answers_id) :
    answers = get_object_or_404(Answers, pk=answers_id)
    if request.user.id != answers.username_id :
        messages.error(request, '확인할 권한이 없습니다.')
        return redirect('tsv:my_page')
    context = {'answers' : answers}
    return render(request, 'tsv/detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Today Sv</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div>
                <strong class="error_field">{{ field.label }}: </strong><span class="error">{{ error }}</span>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div>
            <strong class="error">{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<div class="navbar">
    <img class="logo" src="{% static 'images/today_logo.png' %}" onclick="location.href='{% url 'tsv:index' %}'" />
    <div class="right">
        {% if user.is_authenticated %}
        <a class="username_txt" href="{% url 'tsv:my_page' %}">{{ user.username }}님</a>
        <a class="logout_txt" href="{% url 'common:logout' %}">Sign out</a>
        {% else %}
        <a class="login_txt" href="{% url 'common:login' %}">Sign in</a>
        {% endif %}
    </div>
</div>